name = "astro-turso-blog"
compatibility_date = "2023-07-10"

[vars]
TURSO_DATABASE_URL = "libsql://parai-tarframework.turso.io"

[env.production]
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MTk5OTEwMzYsImlkIjoiOGFhNjljYmItMGJlMC00ZmJlLWE5MWItMjA3Mjg0YjczMjFhIn0.alvKn3gZ24wu4Ow4VOOE40__o92wSQYGqFe6Y3aQyjdV9lBNPa2_jvEwkg7gfF54iNT0UxfWg6wuVone8eOgAA"